/*--------------------------------------------------------------------- NVMH5 -|----------------------
Path:  Sdk\Media\programs\D3D9_StencilShadow\
File:  Constants_StencilShadow.h

Copyright NVIDIA Corporation 2003
TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THIS SOFTWARE IS PROVIDED *AS IS* AND NVIDIA AND
AND ITS SUPPLIERS DISCLAIM ALL WARRANTIES, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO,
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.  IN NO EVENT SHALL NVIDIA
OR ITS SUPPLIERS BE LIABLE FOR ANY SPECIAL, INCIDENTAL, INDIRECT, OR CONSEQUENTIAL DAMAGES WHATSOEVER
INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF BUSINESS PROFITS, BUSINESS INTERRUPTION, LOSS OF
BUSINESS INFORMATION, OR ANY OTHER PECUNIARY LOSS) ARISING OUT OF THE USE OF OR INABILITY TO USE THIS
SOFTWARE, EVEN IF NVIDIA HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.


Comments:


-------------------------------------------------------------------------------|--------------------*/

#define CV_ZERO					 0
#define CV_ONE					 1
#define CV_FACTORS               7

#define CV_WORLDVIEWPROJ_0		 2
#define CV_WORLDVIEWPROJ_1		 3
#define CV_WORLDVIEWPROJ_2		 4
#define CV_WORLDVIEWPROJ_3		 5

#define CV_SHDVOL_DIST			 6

#define CV_LIGHT_COLOR          19
#define CV_ONE_OVER_LIGHT_RANGE 20

#define CV_LIGHT_POS_OSPACE     21
#define CV_LIGHT_CONST          24
#define CV_FOGPARAMS            25
#define CV_HEIGHT_FOG_PARAMS    26

#define CV_FATNESS_SCALE        27

#define CV_COLOR				28
#define CV_COLORSWITCH			29

// Pixel shader defines
#define CP_HEIGHT_FOG_COLOR     0
