/*********************************************************************NVMH4****
Path:  SDK\MEDIA\programs\D3D9_Glow
File:  Constants.h

Copyright NVIDIA Corporation 2002
TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THIS SOFTWARE IS PROVIDED
*AS IS* AND NVIDIA AND ITS SUPPLIERS DISCLAIM ALL WARRANTIES, EITHER EXPRESS
OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY
AND FITNESS FOR A PARTICULAR PURPOSE.  IN NO EVENT SHALL NVIDIA OR ITS SUPPLIERS
BE LIABLE FOR ANY SPECIAL, INCIDENTAL, INDIRECT, OR CONSEQUENTIAL DAMAGES
WHATSOEVER (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF BUSINESS PROFITS,
BUSINESS INTERRUPTION, LOSS OF BUSINESS INFORMATION, OR ANY OTHER PECUNIARY LOSS)
ARISING OUT OF THE USE OF OR INABILITY TO USE THIS SOFTWARE, EVEN IF NVIDIA HAS
BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.


Comments:

******************************************************************************/

#define	CV_TEXCOORD_OFFSET_0	20
#define	CV_TEXCOORD_OFFSET_1	21
#define	CV_TEXCOORD_OFFSET_2	22
#define	CV_TEXCOORD_OFFSET_3	23
#define	CV_TEXCOORD_OFFSET_4	24
#define	CV_TEXCOORD_OFFSET_5	25
#define	CV_TEXCOORD_OFFSET_6	26
#define	CV_TEXCOORD_OFFSET_7	27

#define  CP_WEIGHT_0			0
#define NCP_WEIGHT_0			c0
#define NCP_WEIGHT_1			c1
#define NCP_WEIGHT_2			c2
#define NCP_WEIGHT_3			c3
#define NCP_WEIGHT_4			c4
#define NCP_WEIGHT_5			c5
#define NCP_WEIGHT_6			c6
#define NCP_WEIGHT_7			c7

//-------------------------------------

#define  CV_WORLDVIEWPROJ_0		 2
#define NCV_WORLDVIEWPROJ_0		c2
#define  CV_WORLDVIEWPROJ_1		 3
#define NCV_WORLDVIEWPROJ_1		c3
#define  CV_WORLDVIEWPROJ_2		 4
#define NCV_WORLDVIEWPROJ_2		c4
#define  CV_WORLDVIEWPROJ_3		 5
#define NCV_WORLDVIEWPROJ_3		c5









