/*--------------------------------------------------------------------- NVMH5 -|----------------------
Path:  Sdk\Media\programs\D3D9_TwoSidedPolys\
File:  TwoSidedConstants.h

Copyright NVIDIA Corporation 2003
TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THIS SOFTWARE IS PROVIDED *AS IS* AND NVIDIA AND
AND ITS SUPPLIERS DISCLAIM ALL WARRANTIES, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO,
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.  IN NO EVENT SHALL NVIDIA
OR ITS SUPPLIERS BE LIABLE FOR ANY SPECIAL, INCIDENTAL, INDIRECT, OR CONSEQUENTIAL DAMAGES WHATSOEVER
INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF BUSINESS PROFITS, BUSINESS INTERRUPTION, LOSS OF
BUSINESS INFORMATION, OR ANY OTHER PECUNIARY LOSS) ARISING OUT OF THE USE OF OR INABILITY TO USE THIS
SOFTWARE, EVEN IF NVIDIA HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.


Comments:


-------------------------------------------------------------------------------|--------------------*/

#define CV_ZERO    0
#define CV_ONE     1

#define CV_WORLDVIEWPROJ_0		2
#define CV_WORLDVIEWPROJ_1		3
#define CV_WORLDVIEWPROJ_2		4
#define CV_WORLDVIEWPROJ_3		5

#define CV_WORLDVIEW_0			6
#define CV_WORLDVIEW_1			7
#define CV_WORLDVIEW_2			8
#define CV_WORLDVIEW_3			9

#define CV_INV_WORLD_0			10
#define CV_INV_WORLD_1			11
#define CV_INV_WORLD_2			12
#define CV_INV_WORLD_3			13

#define CV_WORLD_0				14
#define CV_WORLD_1				15
#define CV_WORLD_2				16
#define CV_WORLD_3				17

#define CV_HALF                 18

#define CV_LIGHT_COLOR          19
#define CV_ONE_OVER_LIGHT_RANGE 20

#define CV_LIGHT_POS_OSPACE     21
#define CV_EYE_POS_OSPACE       22

#define CV_EYE_VECTOR			23
#define CV_LIGHT_CONST          24


// Pixel shader defines
#define CP_EYE_VECTOR 0

